server:
  port: 8400
spring:
  datasource:
    name: demo
    url: jdbc:mysql://localhost:3306/demo_01?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
# mybatis相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    # 打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 异步线程池配置
async:
  executor:
    thread:
      # 核心线程数
      core_pool_size: 4
      # 最大线程数
      max_pool_size: 8
      # 队列的大小
      queue_capacity: 100
      # 线程名称
      name:
        prefix: async-thread-

