server:
  port: 8400
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/demo_01?useSSL=false&autoReconnect=true&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave:
          url: jdbc:mysql://172.23.168.70:3306/dynamic?useSSL=false&autoReconnect=true&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
#    name: demo
#    url: jdbc:mysql://localhost:3306/demo_01?useSSL=false&autoReconnect=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
# mybatis相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    # 打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 异步线程池配置
async:
  executor:
    thread:
      # 核心线程数
      core_pool_size: 4
      # 最大线程数
      max_pool_size: 8
      # 队列的大小
      queue_capacity: 100
      # 线程名称
      name:
        prefix: async-thread-

